print("Hello, Python!")
print("My name is", "What")
print("Monty Python")
print()
print("My name is", "Python", end="   ")
print("Monty Python")
print()
print("My", "name is", "Python", "Monty", "Python", sep="-")
print()
print("Programming", "fundamentals", "in", sep="***", end="...")
print("Python")
